name: Apps Build CI

env:
  NODE_OPTIONS: --max-old-space-size=1024

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        apps: ['node-app', 'react-app', 'umi-app', 'vite-app', 'vite-react-app']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: latest
        run_install: true

    - run: pnpm run --filter ${{ matrix.package }} test
